# helpful link:
#https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages


matrix:
  include:
    - language: bash
      compiler: gcc
      dist: xenial
      before_script:
        # Install "shunit2"
        - git clone https://github.com/kward/shunit2 shunit2
      script:
        - source setup_gcc.sh
        - make clean
        - make
        - bash tests/test_simple.sh

